//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumSong
    {
        public int AlbumID { get; set; }
        public int SongID { get; set; }
        public Nullable<byte> Number { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Song Song { get; set; }
    }
}
