//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartReleaseSong
    {
        public int ChartReleaseID { get; set; }
        public int SongID { get; set; }
        public short Number { get; set; }
    
        public virtual Song Song { get; set; }
        public virtual ChartReleas ChartReleas { get; set; }
    }
}
