//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscogsSearchResult
    {
        public int UniqueId { get; set; }
        public int QueryId { get; set; }
        public Nullable<int> Id { get; set; }
        public string Title { get; set; }
        public Nullable<short> Year { get; set; }
        public string Country { get; set; }
        public string Genre { get; set; }
        public string Style { get; set; }
        public string Format { get; set; }
        public string Uri { get; set; }
        public string CoverImage { get; set; }
        public string Thumb { get; set; }
    
        public virtual DiscogsSearchQuery DiscogsSearchQuery { get; set; }
    }
}
