//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResult
    {
        public string ID { get; set; }
        public string Artist { get; set; }
        public string Title { get; set; }
        public string VideoImageURL { get; set; }
        public string Lyrics { get; set; }
        public string VideoID { get; set; }
    
        public virtual Video Video { get; set; }
    }
}
