//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Song()
        {
            this.AlbumSongs = new HashSet<AlbumSong>();
            this.PlaylistSongs = new HashSet<PlaylistSong>();
            this.UserSongs = new HashSet<UserSong>();
            this.SongArtists = new HashSet<SongArtist>();
            this.ChartReleaseSongs = new HashSet<ChartReleaseSong>();
        }
    
        public int ID { get; set; }
        public string Hash { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public string ArtistName { get; set; }
        public string Title { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> Released { get; set; }
        public string VideoID { get; set; }
        public string SpotifyID { get; set; }
        public string WikiURL { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> ConnectedID { get; set; }
        public bool IsLocked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumSong> AlbumSongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistSong> PlaylistSongs { get; set; }
        public virtual Video Video { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSong> UserSongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongArtist> SongArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartReleaseSong> ChartReleaseSongs { get; set; }
        public virtual Artist Artist { get; set; }
    }
}
